import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from './api';
import type { Appointment, Doctor, Patient } from './types';
import { idOf } from './types';
import { Activity, CalendarDays, Check, ChevronRight, CircleAlert, Clock3, HeartPulse, LoaderCircle, Plus, Search, ShieldCheck, Stethoscope, Trash2, UserRound, Users, X } from 'lucide-react';
import './styles.css';

const navItems = [{ key: 'overview', label: 'Overview', icon: Activity }, { key: 'patients', label: 'Patients', icon: Users }, { key: 'doctors', label: 'Doctors', icon: Stethoscope }, { key: 'appointments', label: 'Appointments', icon: CalendarDays }];
type View = typeof navItems[number]['key'];

function App() {
  const [view, setView] = useState<View>('overview');
  const [patients, setPatients] = useState<Patient[]>([]);
  const [doctors, setDoctors] = useState<Doctor[]>([]);
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [showPatientForm, setShowPatientForm] = useState(false);
  const [showDoctorForm, setShowDoctorForm] = useState(false);

  const load = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const [p, d] = await Promise.all([api.patients(), api.doctors()]);
      setPatients(p || []); setDoctors(d || []);
      const lists = await Promise.all((p || []).slice(0, 5).map(x => api.appointmentsForPatient(idOf(x)).catch(() => [])));
      setAppointments(lists.flat());
    } catch (e) { setError(e instanceof Error ? e.message : 'Could not connect to the API.'); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { load(); }, [load]);

  const title = navItems.find(x => x.key === view)?.label || 'Overview';
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><HeartPulse size={21} /></div><div><strong>CarePoint</strong><span>Clinic operations</span></div></div><nav>{navItems.map(({ key, label, icon: Icon }) => <button key={key} className={view === key ? 'nav-item active' : 'nav-item'} onClick={() => setView(key)}><Icon size={18} />{label}</button>)}</nav><div className="sidebar-footer"><ShieldCheck size={16} />API v1 connected</div></aside>
    <main className="main"><header className="topbar"><div><p className="eyebrow">CLINIC BOOKING API</p><h1>{title}</h1></div><button className="avatar">DU</button></header>
      {error && <div className="alert"><CircleAlert size={18} /><span>{error}</span><button onClick={load}><Activity size={15}/> Retry</button></div>}
      {loading ? <div className="loading"><LoaderCircle className="spin" size={28}/><span>Loading clinic data…</span></div> : view === 'overview' ? <Overview patients={patients} doctors={doctors} appointments={appointments} onNavigate={setView} /> : view === 'patients' ? <Patients patients={patients} onAdd={() => setShowPatientForm(true)} onDelete={async id => { await api.deletePatient(id); load(); }} /> : view === 'doctors' ? <Doctors doctors={doctors} onAdd={() => setShowDoctorForm(true)} /> : <Appointments appointments={appointments} onAction={async (id, action) => { if (action === 'confirm') await api.confirmAppointment(id); else await api.cancelAppointment(id); load(); }} />}
    </main>
    {showPatientForm && <PatientForm onClose={() => setShowPatientForm(false)} onSaved={() => { setShowPatientForm(false); load(); }} />}
    {showDoctorForm && <DoctorForm onClose={() => setShowDoctorForm(false)} onSaved={() => { setShowDoctorForm(false); load(); }} />}
  </div>;
}

function Overview({ patients, doctors, appointments, onNavigate }: { patients: Patient[]; doctors: Doctor[]; appointments: Appointment[]; onNavigate: (v: View) => void }) { return <><section className="hero"><div><p className="eyebrow light">GOOD MORNING, ADMIN</p><h2>Your clinic, at a glance.</h2><p>Keep every patient, provider and appointment moving smoothly.</p></div><div className="hero-orb"><HeartPulse size={58}/></div></section><div className="stat-grid"><Stat icon={Users} label="Total patients" value={patients.length} tone="purple" /><Stat icon={Stethoscope} label="Active doctors" value={doctors.filter(d => d.is_active !== false).length} tone="blue" /><Stat icon={CalendarDays} label="Appointments" value={appointments.length} tone="orange" /><Stat icon={Clock3} label="Scheduled" value={appointments.filter(a => a.status === 'Scheduled').length} tone="green" /></div><section className="content-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">QUICK ACTIONS</p><h3>Get things done</h3></div></div><div className="quick-actions"><button onClick={() => onNavigate('patients')}><UserRound /><span><b>Manage patients</b><small>View or register patients</small></span><ChevronRight /></button><button onClick={() => onNavigate('doctors')}><Stethoscope /><span><b>Manage doctors</b><small>Review your care team</small></span><ChevronRight /></button><button onClick={() => onNavigate('appointments')}><CalendarDays /><span><b>Review appointments</b><small>Confirm or cancel visits</small></span><ChevronRight /></button></div></div><div className="panel insight"><p className="eyebrow">SYSTEM STATUS</p><h3>Everything is healthy</h3><div className="status-line"><span className="status-dot"/>Backend API online</div><div className="status-line"><span className="status-dot"/>MongoDB data available</div><div className="status-line"><span className="status-dot"/>Tracing enabled via Jaeger</div></div></section></> }
function Stat({ icon: Icon, label, value, tone }: { icon: typeof Users; label: string; value: number; tone: string }) { return <div className="stat"><div className={`stat-icon ${tone}`}><Icon size={20}/></div><div><span>{label}</span><strong>{value}</strong></div></div> }
function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{description}</p></div>{action}</div> }
function Patients({ patients, onAdd, onDelete }: { patients: Patient[]; onAdd: () => void; onDelete: (id: string) => void }) { const [query, setQuery] = useState(''); const filtered = patients.filter(p => p.name.toLowerCase().includes(query.toLowerCase())); return <><PageHeader eyebrow="PATIENT DIRECTORY" title="Patients" description="Manage patient records and contact information." action={<button className="primary" onClick={onAdd}><Plus size={17}/> Register patient</button>} /><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search patients…" value={query} onChange={e => setQuery(e.target.value)} /></div><span className="muted">{filtered.length} records</span></div><div className="panel table-wrap"><table><thead><tr><th>Patient</th><th>Date of birth</th><th>Gender</th><th>Contact</th><th></th></tr></thead><tbody>{filtered.map(p => <tr key={idOf(p)}><td><div className="person"><div className="person-avatar purple-bg">{p.name.slice(0, 2).toUpperCase()}</div><div><b>{p.name}</b><small>{idOf(p)}</small></div></div></td><td>{p.dob}</td><td><span className="tag">{p.gender}</span></td><td>{p.contact?.email || '—'}</td><td><button className="icon-button danger" onClick={() => onDelete(idOf(p))}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!filtered.length && <Empty text="No patients found" />}</div></> }
function Doctors({ doctors, onAdd }: { doctors: Doctor[]; onAdd: () => void }) { return <><PageHeader eyebrow="CARE TEAM" title="Doctors" description="Manage practitioners and their availability." action={<button className="primary" onClick={onAdd}><Plus size={17}/> Add doctor</button>} /><div className="doctor-grid">{doctors.map(d => <div className="panel doctor-card" key={idOf(d)}><div className="doctor-top"><div className="person-avatar blue-bg"><Stethoscope size={21}/></div><span className={d.is_active === false ? 'status inactive' : 'status'}>{d.is_active === false ? 'Inactive' : 'Active'}</span></div><h3>{d.name}</h3><p className="muted">{d.license_num}</p><div className="specialties">{d.specialties.map(s => <span className="tag" key={s}>{s}</span>)}</div><div className="doctor-footer"><span><CalendarDays size={15}/> Schedule</span><ChevronRight size={16}/></div></div>)}</div>{!doctors.length && <Empty text="No doctors found" />}</> }
function Appointments({ appointments, onAction }: { appointments: Appointment[]; onAction: (id: string, action: 'confirm' | 'cancel') => void }) { return <><PageHeader eyebrow="VISIT PLANNER" title="Appointments" description="Keep track of upcoming visits and booking status." /><div className="panel table-wrap"><table><thead><tr><th>Appointment</th><th>Specialty</th><th>Schedule</th><th>Status</th><th>Actions</th></tr></thead><tbody>{appointments.map(a => <tr key={idOf(a)}><td><div className="person"><div className="person-avatar orange-bg"><CalendarDays size={17}/></div><div><b>{idOf(a).slice(0, 14) || a.slot_id}</b><small>Patient: {a.patient_id}</small></div></div></td><td>{a.specialty}</td><td>{a.start_time ? new Date(a.start_time).toLocaleString() : 'Slot ' + a.slot_id}</td><td><span className={`status ${a.status.toLowerCase()}`}>{a.status}</span></td><td><div className="row-actions">{a.status === 'Scheduled' && <><button className="small-button confirm" onClick={() => onAction(idOf(a), 'confirm')}><Check size={14}/> Confirm</button><button className="small-button cancel" onClick={() => onAction(idOf(a), 'cancel')}><X size={14}/> Cancel</button></>}</div></td></tr>)}</tbody></table>{!appointments.length && <Empty text="No appointments found" />}</div></> }
function Empty({ text }: { text: string }) { return <div className="empty"><CalendarDays size={24}/><span>{text}</span></div> }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><p className="eyebrow">NEW RECORD</p><h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X/></button></div>{children}</div></div> }
function PatientForm({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const [form, setForm] = useState({ name: '', dob: '', gender: 'female', phone: '', email: '', address: '' }); const [saving, setSaving] = useState(false); const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); try { await api.createPatient({ name: form.name, dob: form.dob, gender: form.gender, contact_info: { phone: form.phone, email: form.email, address: form.address } }); onSaved(); } catch { alert('Unable to register patient. Check the API and form values.'); } finally { setSaving(false); } }; return <Modal title="Register patient" onClose={onClose}><form onSubmit={submit} className="form-grid"><label>Full name<input required value={form.name} onChange={e => setForm({...form, name: e.target.value})}/></label><label>Date of birth<input required type="date" value={form.dob} onChange={e => setForm({...form, dob: e.target.value})}/></label><label>Gender<select value={form.gender} onChange={e => setForm({...form, gender: e.target.value})}><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option></select></label><label>Phone<input required value={form.phone} onChange={e => setForm({...form, phone: e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({...form, email: e.target.value})}/></label><label className="full">Address<input required value={form.address} onChange={e => setForm({...form, address: e.target.value})}/></label><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving ? 'Saving…' : 'Register patient'}</button></div></form></Modal> }
function DoctorForm({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const [form, setForm] = useState({ name: '', license_num: '', specialties: 'gp' }); const submit = async (e: React.FormEvent) => { e.preventDefault(); try { await api.createDoctor({ ...form, specialties: form.specialties.split(',').map(s => s.trim()).filter(Boolean) }); onSaved(); } catch { alert('Unable to add doctor. Supported specialties include gp, derm, neuro and cardio.'); } }; return <Modal title="Add doctor" onClose={onClose}><form onSubmit={submit} className="form-grid"><label className="full">Full name<input required placeholder="Dr. Maya Chen" value={form.name} onChange={e => setForm({...form, name: e.target.value})}/></label><label>License number<input required value={form.license_num} onChange={e => setForm({...form, license_num: e.target.value})}/></label><label>Specialties<input required placeholder="gp, derm" value={form.specialties} onChange={e => setForm({...form, specialties: e.target.value})}/></label><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Add doctor</button></div></form></Modal> }
export default App;
